[theme]
# Primary accent color for interactive elements
primaryColor = "#4F8BF9"

# Background color for the main content area
backgroundColor = "#0E1117"

# Background color for sidebar and most interactive widgets
secondaryBackgroundColor = "#1A2332"

# Color used for almost all text
textColor = "#FAFAFA"

# Font family for all text in the app, except code blocks
# Accepted values (serif | sans serif | monospace) 
# Default: "sans serif"
font = "sans serif"

[server]
headless = true
address = "0.0.0.0"
port = 5000